server:
  port: 8888
spring:
#  profiles:
#    active: native
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URL}
          force-pull: true
          username: ${USER}
          password: ${PASS}
#        native:
#          search-locations: D:/Users/edson/IntelliJIdea/testes/microservices-springboot/config-micro-services
